import fs from 'fs';
import path from 'path';
import { Meeting, Reminder, DailyGoal, SocialDraft, BrowserTabRule, BrowserAutomationCommand } from '../src/types.js';

interface DatabaseSchema {
  meetings: Meeting[];
  reminders: Reminder[];
  goals: DailyGoal[];
  socialDrafts: SocialDraft[];
  tabRules: BrowserTabRule[];
  automationLogs: BrowserAutomationCommand[];
  stats: {
    totalRequests: number;
    fallbackEvents: number;
    startTime: string;
  };
}

const DATA_DIR = path.join(process.cwd(), 'data');
const DB_FILE = path.join(DATA_DIR, 'jarvis-db.json');

const INITIAL_DATA: DatabaseSchema = {
  meetings: [
    {
      id: 'meet-1',
      title: 'AI Product Strategy Sync',
      date: '2026-09-11',
      time: '14:00',
      durationMinutes: 45,
      participants: ['Alex Vance (Product)', 'Sarah Lin (Engineering)'],
      notes: 'Review Q4 agent automation deliverables and free-tier multi-model failover metrics.',
      status: 'confirmed',
      createdAt: new Date().toISOString()
    },
    {
      id: 'meet-2',
      title: 'Content Pipeline & YouTube Outlier Review',
      date: '2026-09-12',
      time: '10:30',
      durationMinutes: 30,
      participants: ['Creator Team', 'Editor'],
      notes: 'Examine high-engagement hook formats and scheduled video drafts.',
      status: 'confirmed',
      createdAt: new Date().toISOString()
    }
  ],
  reminders: [
    {
      id: 'rem-1',
      title: 'Review and approve pending Instagram reel draft',
      dueDate: 'Today, 18:00',
      priority: 'high',
      completed: false,
      category: 'content',
      createdAt: new Date().toISOString()
    },
    {
      id: 'rem-2',
      title: 'Check Groq and Gemini free-tier rate limits',
      dueDate: 'Tomorrow, 09:00',
      priority: 'medium',
      completed: true,
      category: 'work',
      createdAt: new Date().toISOString()
    },
    {
      id: 'rem-3',
      title: 'Hydrate and take 15-min screen rest',
      dueDate: 'Every 2 hours',
      priority: 'low',
      completed: false,
      category: 'health',
      createdAt: new Date().toISOString()
    }
  ],
  goals: [
    {
      id: 'goal-1',
      title: 'Maintain 99.9% agent uptime with multi-model failover',
      target: 'Zero unhandled API rate limits',
      completed: true,
      progressPercent: 100
    },
    {
      id: 'goal-2',
      title: 'Publish 3 approved high-yield social posts this week',
      target: '3 posts (YouTube, IG, FB)',
      completed: false,
      progressPercent: 66
    },
    {
      id: 'goal-3',
      title: 'Summarize 5 technical whitepapers & slide decks',
      target: '5 documents processed',
      completed: false,
      progressPercent: 40
    }
  ],
  socialDrafts: [
    {
      id: 'draft-1',
      platform: 'youtube',
      title: 'How I Built a 100% Free Autonomous AI Agent in a Week',
      content: 'Most people spend $200+/month on AI API bills. In this breakdown, I show you how to build "Jarvis" using only free-tier cloud models with automated cascade fallback across Google Gemini and Groq. Zero cost, zero downtime.\n\nKey chapters:\n0:00 Intro & Architecture\n2:30 Multi-Model Failover\n6:10 Browser Control Extension\n10:45 Draft-and-Approve Workflow',
      tags: ['#AIAgent', '#TechDIY', '#OpenSource', '#Gemini', '#Productivity'],
      status: 'pending_approval',
      createdAt: new Date(Date.now() - 3600000).toISOString(),
      estimatedReach: '12K - 25K views',
      approvalHistory: ['Generated by Jarvis Content Skill', 'Awaiting user sign-off']
    },
    {
      id: 'draft-2',
      platform: 'instagram',
      title: 'The Golden Rule of AI Automation: Keep the Human in the Loop 🛡️',
      content: 'Never let an AI post autonomously to your social channels. Here is why our Jarvis web assistant enforces an explicit "Draft & Approve" gate for every YouTube, IG, and FB post.\n\nDrop a comment if you want the open-source repo link! 👇',
      tags: ['#TechTips', '#ArtificialIntelligence', '#SoftwareDev', '#Jarvis'],
      status: 'pending_approval',
      createdAt: new Date(Date.now() - 7200000).toISOString(),
      estimatedReach: '3.5K impressions',
      approvalHistory: ['Drafted via Instagram Skill']
    }
  ],
  tabRules: [
    {
      id: 'rule-1',
      urlPattern: 'https://www.youtube.com/*',
      title: 'YouTube (Video Play/Pause & Scroll)',
      isAllowed: true,
      lastAction: 'Pause video command allowed',
      addedAt: new Date().toISOString()
    },
    {
      id: 'rule-2',
      urlPattern: 'https://news.ycombinator.com/*',
      title: 'Hacker News (Scroll Reading)',
      isAllowed: true,
      lastAction: 'Scroll down 600px',
      addedAt: new Date().toISOString()
    },
    {
      id: 'rule-3',
      urlPattern: 'https://twitter.com/*',
      title: 'X / Twitter (Restricted by default)',
      isAllowed: false,
      lastAction: 'Access blocked - pending explicit permission',
      addedAt: new Date().toISOString()
    }
  ],
  automationLogs: [
    {
      id: 'log-1',
      action: 'scroll_down',
      tabUrl: 'https://news.ycombinator.com/',
      tabTitle: 'Hacker News Frontpage',
      timestamp: new Date(Date.now() - 180000).toISOString(),
      status: 'executed',
      details: 'Scrolled page down 500px on approved domain.'
    },
    {
      id: 'log-2',
      action: 'pause_video',
      tabUrl: 'https://www.youtube.com/watch?v=jfKfPfyJRdk',
      tabTitle: 'Lofi Hip Hop Radio',
      timestamp: new Date(Date.now() - 60000).toISOString(),
      status: 'executed',
      details: 'Triggered HTML5 video.pause() on allowed tab.'
    }
  ],
  stats: {
    totalRequests: 14,
    fallbackEvents: 0,
    startTime: new Date().toISOString()
  }
};

class StorageManager {
  private data: DatabaseSchema;

  constructor() {
    this.data = this.loadData();
  }

  private loadData(): DatabaseSchema {
    try {
      if (!fs.existsSync(DATA_DIR)) {
        fs.mkdirSync(DATA_DIR, { recursive: true });
      }
      if (fs.existsSync(DB_FILE)) {
        const content = fs.readFileSync(DB_FILE, 'utf-8');
        return JSON.parse(content);
      }
    } catch (err) {
      console.warn('Failed to read database file, initializing defaults:', err);
    }
    this.saveData(INITIAL_DATA);
    return INITIAL_DATA;
  }

  private saveData(data: DatabaseSchema) {
    try {
      if (!fs.existsSync(DATA_DIR)) {
        fs.mkdirSync(DATA_DIR, { recursive: true });
      }
      fs.writeFileSync(DB_FILE, JSON.stringify(data, null, 2), 'utf-8');
    } catch (err) {
      console.error('Failed to write database file:', err);
    }
  }

  // Meetings
  getMeetings(): Meeting[] {
    return this.data.meetings;
  }

  addMeeting(meeting: Omit<Meeting, 'id' | 'createdAt'>): Meeting {
    const newMeeting: Meeting = {
      ...meeting,
      id: `meet-${Date.now()}`,
      createdAt: new Date().toISOString()
    };
    this.data.meetings.unshift(newMeeting);
    this.saveData(this.data);
    return newMeeting;
  }

  deleteMeeting(id: string): boolean {
    const initialLen = this.data.meetings.length;
    this.data.meetings = this.data.meetings.filter(m => m.id !== id);
    this.saveData(this.data);
    return this.data.meetings.length < initialLen;
  }

  // Reminders
  getReminders(): Reminder[] {
    return this.data.reminders;
  }

  addReminder(reminder: Omit<Reminder, 'id' | 'createdAt'>): Reminder {
    const newRem: Reminder = {
      ...reminder,
      id: `rem-${Date.now()}`,
      createdAt: new Date().toISOString()
    };
    this.data.reminders.unshift(newRem);
    this.saveData(this.data);
    return newRem;
  }

  toggleReminder(id: string): Reminder | null {
    const item = this.data.reminders.find(r => r.id === id);
    if (item) {
      item.completed = !item.completed;
      this.saveData(this.data);
      return item;
    }
    return null;
  }

  deleteReminder(id: string): boolean {
    const initialLen = this.data.reminders.length;
    this.data.reminders = this.data.reminders.filter(r => r.id !== id);
    this.saveData(this.data);
    return this.data.reminders.length < initialLen;
  }

  // Goals
  getGoals(): DailyGoal[] {
    return this.data.goals;
  }

  addGoal(goal: Omit<DailyGoal, 'id'>): DailyGoal {
    const newGoal: DailyGoal = {
      ...goal,
      id: `goal-${Date.now()}`
    };
    this.data.goals.push(newGoal);
    this.saveData(this.data);
    return newGoal;
  }

  updateGoal(id: string, updates: Partial<DailyGoal>): DailyGoal | null {
    const item = this.data.goals.find(g => g.id === id);
    if (item) {
      Object.assign(item, updates);
      this.saveData(this.data);
      return item;
    }
    return null;
  }

  // Social Drafts (Approval workflow)
  getSocialDrafts(): SocialDraft[] {
    return this.data.socialDrafts;
  }

  addSocialDraft(draft: Omit<SocialDraft, 'id' | 'createdAt' | 'status'>): SocialDraft {
    const newDraft: SocialDraft = {
      ...draft,
      id: `draft-${Date.now()}`,
      status: 'pending_approval',
      createdAt: new Date().toISOString(),
      approvalHistory: ['Drafted via Jarvis AI Action Engine - Pending User Review']
    };
    this.data.socialDrafts.unshift(newDraft);
    this.saveData(this.data);
    return newDraft;
  }

  updateDraftStatus(id: string, status: SocialDraft['status'], notes?: string): SocialDraft | null {
    const item = this.data.socialDrafts.find(d => d.id === id);
    if (item) {
      item.status = status;
      item.updatedAt = new Date().toISOString();
      if (!item.approvalHistory) item.approvalHistory = [];
      const actionText = status === 'approved' 
        ? `Approved by User for publication (${notes || 'Direct UI confirmation'})` 
        : status === 'rejected'
        ? `Rejected by User (${notes || 'Disapproved in UI'})`
        : status === 'published'
        ? `Dispatched to ${item.platform.toUpperCase()} API`
        : `Updated to ${status}`;
      item.approvalHistory.push(actionText);
      this.saveData(this.data);
      return item;
    }
    return null;
  }

  // Tab Rules & Automation
  getTabRules(): BrowserTabRule[] {
    return this.data.tabRules;
  }

  addTabRule(rule: Omit<BrowserTabRule, 'id' | 'addedAt'>): BrowserTabRule {
    const newRule: BrowserTabRule = {
      ...rule,
      id: `rule-${Date.now()}`,
      addedAt: new Date().toISOString()
    };
    this.data.tabRules.push(newRule);
    this.saveData(this.data);
    return newRule;
  }

  toggleTabRule(id: string): BrowserTabRule | null {
    const rule = this.data.tabRules.find(r => r.id === id);
    if (rule) {
      rule.isAllowed = !rule.isAllowed;
      this.saveData(this.data);
      return rule;
    }
    return null;
  }

  getAutomationLogs(): BrowserAutomationCommand[] {
    return this.data.automationLogs;
  }

  recordAutomationCommand(cmd: Omit<BrowserAutomationCommand, 'id' | 'timestamp'>): BrowserAutomationCommand {
    const newLog: BrowserAutomationCommand = {
      ...cmd,
      id: `auto-${Date.now()}`,
      timestamp: new Date().toISOString()
    };
    this.data.automationLogs.unshift(newLog);
    if (this.data.automationLogs.length > 50) {
      this.data.automationLogs = this.data.automationLogs.slice(0, 50);
    }
    this.saveData(this.data);
    return newLog;
  }

  // Stats
  recordRequest() {
    this.data.stats.totalRequests += 1;
    this.saveData(this.data);
  }

  recordFallback() {
    this.data.stats.fallbackEvents += 1;
    this.saveData(this.data);
  }

  getStats() {
    return {
      ...this.data.stats,
      meetingsCount: this.data.meetings.length,
      pendingDraftsCount: this.data.socialDrafts.filter(d => d.status === 'pending_approval').length,
      remindersCount: this.data.reminders.filter(r => !r.completed).length,
      goalsCount: this.data.goals.length
    };
  }
}

export const storage = new StorageManager();
